# +----------------------------------------------------+
# <                   Houses config                    >
# +----------------------------------------------------+
# DO NOT USE TAB INDENTION. Indent with spaces instead

# This will make players get the specified rank (permission group) for the class he/she buys 
use-class-ranks: true

# Enabling this will let you leave the price row blank on signs and let the plugin automatically set the right price
use-class-prices: true

# It is recommended to have autoclosing doors to avoid griefing
autoclose-door-delay: 2.5

# Cooldown for "/house home" command in seconds. Use -1 for no cooldown
home-teleport-cooldown: 3

# Put -1 to allowed unlimited houses
maximum-houses: -1

# It is recommended to clean the database on start because a corrupt database 
# will cause trouble when doing database syncronization
clean-database-on-start: true

# Enabling this will allow the house builder to receive the money from the buyer
# instead of the money just disappearing
house-builder-profit: false

# This is the rank (permissions group) the players will get if they become homeless 
homeless: default

# If using class prices, Houses will use this percentage to calculate sell prices on signs
sell-percentage: 75

# Timer to check rent every amount of seconds - Note: Lower values could cause lag
expired-check-timer: 60

# This is where you configure your classes. The staff classses (owner/admin/mod) can not be configured below 
# as they should be added by other staff manually for security reasons.
# There are two example of how classes can be configured below.
classes:
  '1':
    rank: Governor
    price: 500000
    per-day-cost: 20000
    info: The best house there is
  '5':
    rank: Worker
    price: 70000
    per-day-cost: 3000
    info: A decent house for the regular worker

worlds:
  display-worlds: true
