main: com.hektropolis.houses.Houses
name: Houses
version: 2.0
author: Solivero, CC007, steve4744
api-version: 1.13
description: Houses
depend: [Vault]
commands:
  house:
    description: Commands for Houses
    aliases: [houses, h]
